services:
  demo_app:
    build: '.'
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    command: bash -c "(rake db:migrate:status 2>/dev/null || rake db:setup) && rake db:migrate && rails s -b 0.0.0.0"
    container_name: demo_app_example
